# .github/workflows/deploy.yml
name: 自动部署到 GitHub Pages

# 监听 push 到 master 分支
on:
  push:
    branches:
      - master
permissions:
  contents: write

jobs:
  build-and-deploy:
    # 使用最新的 Ubuntu 运行环境
    runs-on: ubuntu-latest

    steps:
      # 1. 检出仓库代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 安装 Node.js（可选：指定与你本地一致的版本）
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. 安装依赖
      - name: Install dependencies
        run: npm install

      # 4. 构建项目
      - name: Build project
        run: export NODE_OPTIONS=--openssl-legacy-provider && npm run build:prod

      # 5. 部署到 gh-pages 分支
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # GitHub 自动提供的令牌，无需自定义
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # 构建输出目录，根据你的项目调整：
          # Vue/Vite 默认是 `dist`；若是 VuePress 则是 docs/.vuepress/dist
          publish_dir: docs/.vuepress/dist
